<Test>
    canvas.before:
        Color:
            rgb: 1, 0, 1
        Rectangle:
            pos: self.pos
            size: self.size

    Widget:
        font_size: 70
        size_hint: None, None
        size: 300, 300
        pos: 100, 100
        canvas.before:
            Color:
                rgb: 1, 1, 0
            Rectangle:
                pos: self.pos
                size: self.size

        Label:
            text: 'a'
            font_size: 70
            size: 70, 70
            pos: self.parent.pos